name: Hello World

on:
  push:
    branches:
      - main
    paths:
      - '.github.workflows/hello-world.yml'
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World, GitHub Actions"