name: Infra S3 Bucket 
on:
  push:
    branches:
      - main
      - infra/s3-bucket-task
    paths:
      - '.github/workflows/infra-s3-workflow.yml'
  pull_request:
     branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: 'us-east-1' 
  S3_BUCKET_NAME: 'github-actions-tf-task-zhyldyz' 

permissions:
  id-token: write
  contents: read
  
jobs:
  tf_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
        # Checkout Repo
      - name: Checkout Code
        uses: actions/checkout@v4

        # Setup terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.12.2
      
       # Configure AWS credentials
      - name: Configure AWS credentials (Static)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: List S3 Buckets
        run: aws s3 ls --region us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan
        working-directory: ./infra

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./infra
 #
  # tf_deploy:
  #   name: Terraform Deploy
  #   needs: tf_plan
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3

  #     - name: Download Plan
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: tfplan
  #         path: ./infra

  #     - name: Terraform Init
  #       run: terraform init
  #       working-directory: ./infra

  #     - name: Terraform Apply
  #       run: terraform apply tfplan
  #       working-directory: ./infra

