name: Custom Scripts and Artifact Upload
on:
  schedule:
    - cron: '5 * * * *'  
      branches:
      - main
      - feauture/artifacts-classwork
      paths:
      - '.github/workflows/session6-artifacts.yml'
  workflow_dispatch:

env: 
  PYTHON_VERSION: '3.12'

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Run Bash Script
        run: | 
          chmod +x scripts/report.sh 
          ./scripts/report.sh
          echo "It is a confirmation that the txt file has been created"
          ls -l scripts/
          cat scripts/bash-report.txt