name: Session 3 Homework Workflow

on:
  push:
    branches: [ "feature/session3-homework" ]
  workflow_dispatch:  # Manually triggered


env: 
  PROJECT_NAME: "Session3 Homework"

jobs:
  info-collection:
    runs-on: ubuntu-latest
    env:
      EMVIRONMENT_TYPE: "Development"
    steps:
      - uses: actions/checkout@v4
      - name: Show All Environment Variables
      - run: |
          echo "The project name is: $PROJECT_NAME"
          echo "The environment type is: $ENVIRONMENT TYPE"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Workflow: ${{ github.workflow }}"

